name: BlissSmp1
version: '1.0'
main: com.blisssmp1.BlissSmp1
api-version: '1.20'
commands:
  firegem:
    description: "spawns the fire gem"
    usage: "/FireGem"
    aliases: [ BlissSmp1]
    permission: bliss.command.firegem
    permission-message: "you do not have permission to run this command"

